config/routes.rb
Boxroom::Application.routes.draw do
  get '/file_exists', :to => 'files#exists'
  get '/signin', :to => 'sessions#new', :as => 'signin'
  get '/home', :to => 'home#index', :as => 'home', path: '/home'
  delete '/signout', :to => 'sessions#destroy'

  # Resources
  resources :admins, :only => [:new, :create]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :reset_password, :except => [:index, :show, :destroy]
  resources :signup, :only => [:edit, :update]
  resources :groups, :except => :show
  resources :files, :except => [:index, :new, :create] do
    get :preview
  end
  resources :share_links, :only => [:index, :show, :destroy]

  resources :users, :except => :show do
    put :extend, :on => :member
  end

  resources :clipboard, :only => [:create, :destroy] do
    post :copy, :on => :member
    post :move, :on => :member
    put :reset, :on => :member
  end

  # Update a collection of permissions
  resources :permissions, :only => :update_multiple do
    put :update_multiple, :on => :collection
  end

  # Nested resources
  resources :folders, :shallow => true, :except => [:new, :create] do
    resources :folders, :only => [:new, :create]
    resources :files, :only => [:new, :create]
  end

  resources :files, :shallow => true, :only => :show do
    resources :share_links, :only => [:new, :create]
  end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => "folders#index"
end

app/models/folder.rb
class Folder < ActiveRecord::Base
  acts_as_tree :order => 'id'

  has_many :user_files, -> { order :attachment_file_name }, :dependent => :destroy
  has_many :permissions, :dependent => :destroy

  attr_accessor :is_copied_folder

  validates_uniqueness_of :name, :scope => :parent_id
  validates_presence_of :name

  before_save :check_for_parent
  after_create :create_permissions, :unless => :is_copied_folder
  before_destroy :dont_destroy_root_folder

  def copy(target_folder, originally_copied_folder = nil)
    new_folder = self.dup
    new_folder.is_copied_folder = true
    new_folder.parent = target_folder
    new_folder.save!

    originally_copied_folder = new_folder if originally_copied_folder.nil?

    # Copy original folder's permissions
    self.permissions.each do |permission|
      new_permission = permission.dup
      new_permission.folder = new_folder
      new_permission.save!
    end

    self.user_files.each do |file|
      file.copy(new_folder)
    end

    # Copy sub-folders recursively
    self.children.each do |folder|
      folder.copy(new_folder, originally_copied_folder) unless folder == originally_copied_folder
    end

    new_folder
  end

  def move(target_folder)
    unless target_folder == self || self.parent_of?(target_folder)
      self.parent = target_folder
      save!
    else
      raise 'You cannot move a folder to its own sub-folder.'
    end
  end

  def copy_permissions_to_children(permissions_to_copy)
    permissions_to_copy.each do |permission|
      attributes = permission.attributes.except('id', 'folder_id', 'group_id')
      Permission.where(:folder_id => children, :group_id => permission.group_id).update_all(attributes)
    end

    # Copy permissions recursively
    children.each do |child|
      child.copy_permissions_to_children(permissions_to_copy) if child.has_children?
    end
  end

  def parent_of?(folder)
    self.children.each do |child|
      if child == folder
        return true
      else
        return child.parent_of?(folder)
      end
    end
    false
  end

  def is_root?
    parent.nil? && !new_record?
  end

  def has_children?
    children.count > 0
  end

  def self.root
    @root_folder ||= find_by_name_and_parent_id('Root folder', nil)
  end

  private

  def check_for_parent
    raise 'Folders must have a parent.' if parent.nil? && name != 'Root folder'
  end

  def create_permissions
    unless is_root?
      parent.permissions.each do |permission|
        Permission.create! do |p|
          p.group = permission.group
          p.folder = self
          p.can_create = permission.can_create
          p.can_read = permission.can_read
          p.can_update = permission.can_update
          p.can_delete = permission.can_delete
        end
      end
    end
  end

  def dont_destroy_root_folder
    raise "Can't delete Root folder" if is_root?
  end
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  before_action :require_existing_folder, :only => [:show, :edit, :update, :destroy]
  before_action :require_existing_target_folder, :only => [:new, :create]
  before_action :require_folder_isnt_root_folder, :only => [:edit, :update, :destroy]

  before_action :require_create_permission, :only => [:new, :create]
  before_action :require_read_permission, :only => :show
  before_action :require_update_permission, :only => [:edit, :update]
  before_action :require_delete_permission, :only => :destroy

  def index
    redirect_to Folder.root
  end

  # Note: @folder is set in require_existing_folder
  def show
  end

  # Note: @target_folder is set in require_existing_target_folder
  def new
    @folder = @target_folder.children.build
  end

  # Note: @target_folder is set in require_existing_target_folder
  def create
    @folder = @target_folder.children.build(permitted_params.folder)

    if @folder.save
      redirect_to @target_folder
    else
      render :action => 'new'
    end
  end

  # Note: @folder is set in require_existing_folder
  def edit
  end

  # Note: @folder is set in require_existing_folder
  def update
    if @folder.update_attributes(permitted_params.folder)
      redirect_to edit_folder_url(@folder), :notice => t(:your_changes_were_saved)
    else
      render :action => 'edit'
    end
  end

  # Note: @folder is set in require_existing_folder
  def destroy
    target_folder = @folder.parent
    @folder.destroy
    redirect_to target_folder
  end

  private

  # get_folder_or_redirect is defined in ApplicationController
  def require_existing_folder
    @folder = get_folder_or_redirect(params[:id])
  end

  def require_folder_isnt_root_folder
    if @folder.is_root?
      redirect_to Folder.root, :alert => t(:cannot_delete_root_folder)
    end
  end

  # Overrides require_delete_permission in ApplicationController
  def require_delete_permission
    unless @folder.is_root? || current_user.can_delete(@folder)
      redirect_to @folder.parent, :alert => t(:no_permissions_for_this_type, :method => t(:delete), :type =>t(:this_folder))
    else
      require_delete_permissions_for(@folder.children)
    end
  end

  def require_delete_permissions_for(folders)
    folders.each do |folder|
      unless current_user.can_delete(folder)
        redirect_to @folder.parent, :alert => t(:no_delete_permissions_for_subfolder)
      else
        # Recursive...
        require_delete_permissions_for(folder.children)
      end
    end
  end
end

app/helpers/folders_helper.rb
module FoldersHelper
  def breadcrumbs(folder, breadcrumbs = '')
    breadcrumbs = "<span class=\"breadcrumb nowrap\">#{link_to(folder.parent.name, folder.parent)}</span>#{breadcrumbs}"
    breadcrumbs = breadcrumbs(folder.parent, breadcrumbs) unless folder.parent == Folder.root
    breadcrumbs.html_safe
  end

  def file_icon(extension)
    if extension && FileTest.exists?(Rails.root.join('app','assets','images','fileicons', "#{extension.downcase}.png"))
      "fileicons/#{extension.downcase}.png"
    else
      'file.png'
    end
  end
end

app/views/folders/_form.html.erb
<%= f.error_messages %>
<div class="form__row">
    <div class="form__label">
        <%= f.label :name, t(:'文件夹名') %>
    </div>
    <div class="form__control">
        <%= f.text_field :name, { :class => 'text_input' } %>
    </div>
</div>
<div class="form-btns clearfix">
    <button type="submit" class="button--light">保 存</button>
    <%= link_to '返 回', @folder.parent, { :class => 'button--light default link-to-button' } %>
</div>

app/views/folders/edit.html.erb
<div class="form__wrapper--center form__wrapper--normal">
    <% content_for :title, '更改文件夹名' -%>

    <h1 class="title--level1"><%= content_for :title %></h1>
    <%= form_for @folder do |f| %>
      <%= render :partial => 'form', :locals => { :f => f } %>
    <% end %>
</div>

app/views/folders/new.html.erb
<div class="form__wrapper--center form__wrapper--normal">
    <% content_for :title, t(:新建文件夹) -%>

    <h1 class="title--level1"><%= content_for :title %></h1>
    <%= form_for [@target_folder, @folder] do |f| %>
      <%= render :partial => 'form', :locals => { :f => f } %>
    <% end %>
</div>

app/views/folders/show.html.erb
<% content_for :title, @folder.name -%>

<h1 class="title--level1"><%= content_for :title %></h1>
<!-- 面包屑 导航 -->
<% unless @folder.is_root? -%>
<p class="clearfix">
  <%= breadcrumbs(@folder) %>
  <span class="breadcrumb nowrap"><%= @folder.name %></span>
</p>
<% end -%>
<!-- 面包屑 导航 end -->
<!-- folders 顶级工具栏 -->
<p class="folder_menu_wrapper">
<% if current_user.can_create(@folder) -%>
  <span class="folder_menu bdr"><%= image_tag('folder_add.png', :alt => t(:create_a_new_folder)) %> <%= link_to t(:新建文件夹), new_folder_folder_path(@folder) %></span>
  <span class="folder_menu bdr"><%= image_tag('file_add.png', :alt => t(:upload_a_file)) %> <%= link_to t(:上传文件), new_folder_file_path(@folder) %></span>
<% end -%>
<% if current_user.member_of_admins? -%>
  <span class="folder_menu" id="permissions_link"><span><%= image_tag('permissions.png', :alt => t(:permissions)) %> <%= link_to t(:授权), '#', :class => 'permissions_link' %></span></span>
<% end -%>
  <span class="folder_menu" id="clipboard_link"><span><%= image_tag('clipboard.png', :alt => t(:clipboard)) %> <%= link_to t(:剪贴板), '#', :class => 'clipboard_link' %></span></span>
</p>
<!-- folders 顶级工具栏 end -->

<div id="files_and_folders" class="table--stripes">
  <table style="width:100%;">
    <tr>
      <th></th>
      <th><%= t :名称 %></th>
      <th><%= t :大小 %></th>
      <th><%= t :修改日期 %></th>
      <th><%= t :操作 %></th>
    </tr>
  <% unless @folder.is_root? -%>
    <tr class="<%= cycle('even','odd') %>">
      <td><%= image_tag('folder.png') %></td>
      <td class="file_name">&uarr; <%= link_to t(:up), @folder.parent, :title => @folder.parent.name %></td>
      <td class="file_size">--</td>
      <td class="file_modified">--</td>
      <td></td>
    </tr>
  <% end -%>
  <% @folder.children.each do |folder| -%>
    <% if current_user.can_read(folder) -%>
    <tr class="<%= cycle('even','odd') %>">
      <td><%= image_tag('folder.png') %></td>
      <td class="file_name"><%= link_to folder.name, folder %></td>
      <td class="file_size">--</td>
      <td class="file_modified"><%= l folder.updated_at, :format => :short %></td>
      <td>
      <% if current_user.can_update(folder) -%>
        <%= link_to image_tag('edit.png', :alt => t(:edit)), edit_folder_path(folder), :title => t(:edit) %>&nbsp;
      <% end -%>
      <% if current_user.can_delete(folder) -%>
        <%= link_to image_tag('delete.png', :alt => t(:delete_item)), folder, :method => :delete, :data => { :confirm => t(:are_you_sure) }, :title => t(:delete_item) %>&nbsp;
      <% end -%>
        <%= link_to image_tag('clipboard_add.png', :alt => t(:add_to_clipboard)),
          { :controller => :clipboard, :action => :create, :id => folder.id, :type => 'folder', :folder_id => @folder, :authenticity_token => form_authenticity_token },
          :method => :post, :title => t(:add_to_clipboard)
        %>
      </td>
    </tr>
    <% end -%>
  <% end -%>
  <% @folder.user_files.each do |file| -%>
    <% if current_user.can_read(@folder) -%>
    <tr class="<%= cycle('even','odd') %>">
      <td><%= image_tag(file_icon(file.extension)) %></td>
      <td class="file_name">
        <%if file.is_image? || file.is_document?%>
          <div style="width:250px;font-size:0.8em;color:#444;">
            <%if file.is_image?%>
              <img src="<%=file_path(file)%>" alt="" style="border:1px solid #aaa;border-radius:2px; max-width:100px; max-height:100px;">
              <br><%=file.attachment_file_name%>
            <%else%>
              <%= link_to file.attachment_file_name, file_path(file), :title => "#{t(:download)} #{file.attachment_file_name}" %>
            <%end%>
            <br>
            <a target="_blank" href="<%=file_preview_path(file)%>">Preview</a>
            <a href="<%=file_path(file)%>">Download</a>
          </div>
        <%elsif (file.is_url? || file.is_text?)%>
          <a target="_blank" href="<%=file_preview_path(file)%>"><%=file.attachment_file_name%></a>
        <%else%>
          <%= link_to file.attachment_file_name, file_path(file), :title => "#{t(:download)} #{file.attachment_file_name}" %>
        <%end%>
      </td>
      <td class="file_size"><%= number_to_human_size(file.attachment_file_size, :locale => I18n.locale) %></td>
      <td class="file_modified"><%= l file.updated_at, :format => :short %></td>
      <td>
      <% if current_user.can_update(file.folder) -%>
        <%= link_to image_tag('edit.png', :alt => t(:edit)), edit_file_path(file), :title => t(:edit) %>&nbsp;
      <% end -%>
      <% if current_user.can_delete(file.folder) -%>
        <%= link_to image_tag('delete.png', :alt => t(:delete_item)), file_path(file), :method => :delete, :data => { :confirm => t(:are_you_sure) }, :title => t(:delete_item) %>&nbsp;
      <% end -%>
        <%= link_to image_tag('clipboard_add.png', :alt => t(:add_to_clipboard)),
          { :controller => :clipboard, :action => :create, :id => file.id, :type => 'file', :folder_id => @folder, :authenticity_token => form_authenticity_token },
          :method => :post, :title => t(:add_to_clipboard)
        %>&nbsp;
        <%= link_to image_tag('share.png', :alt => t(:share)), new_file_share_link_path(file), :title => t(:share) %>
      </td>
    </tr>
    <% end -%>
  <% end -%>
  </table>
</div>
<% if current_user.member_of_admins? -%>
<div id="permissions" style="display:none;">
  <%= render 'permissions/form' %>
</div>
<% end -%>
<div id="clipboard" style="display:none;">
  <%= render 'clipboard/show' %>
</div>