config/routes.rb
Boxroom::Application.routes.draw do
  get '/file_exists', :to => 'files#exists'
  get '/signin', :to => 'sessions#new', :as => 'signin'
  get '/home', :to => 'home#index', :as => 'home', path: '/home'
  delete '/signout', :to => 'sessions#destroy'

  # Resources
  resources :admins, :only => [:new, :create]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :reset_password, :except => [:index, :show, :destroy]
  resources :signup, :only => [:edit, :update]
  resources :groups, :except => :show
  resources :files, :except => [:index, :new, :create] do
    get :preview
  end
  resources :share_links, :only => [:index, :show, :destroy]

  resources :users, :except => :show do
    put :extend, :on => :member
  end

  resources :clipboard, :only => [:create, :destroy] do
    post :copy, :on => :member
    post :move, :on => :member
    put :reset, :on => :member
  end

  # Update a collection of permissions
  resources :permissions, :only => :update_multiple do
    put :update_multiple, :on => :collection
  end

  # Nested resources
  resources :folders, :shallow => true, :except => [:new, :create] do
    resources :folders, :only => [:new, :create]
    resources :files, :only => [:new, :create]
  end

  resources :files, :shallow => true, :only => :show do
    resources :share_links, :only => [:new, :create]
  end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => "folders#index"
end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :groups
  has_many :share_links  

  attr_accessor :password_confirmation, :password_required, :dont_clear_reset_password_token

  validates_confirmation_of :password
  validates_length_of :password, :in => 6..20, :allow_blank => true
  validates_presence_of :password, :if => :password_required
  validates_presence_of :name, :unless => :new_record?
  validates_presence_of :email
  validates_uniqueness_of :name, :unless => :new_record? && :name_is_blank?
  validates_uniqueness_of :email
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/

  before_create :set_signup_token
  before_save :clear_reset_password_token, :unless => :dont_clear_reset_password_token
  before_update :clear_signup_token
  after_create :create_root_folder_and_admins_group, :if => :is_admin
  before_destroy :dont_destroy_admin

  %w{create read update delete}.each do |method|
    define_method "can_#{method}" do |folder|
      has_permission = false

      Permission.where(:group_id => groups, :folder_id => folder.id).each do |permission|
        has_permission = permission.send("can_#{method}")
        break if has_permission
      end

      has_permission
    end
  end

  def password
    @password
  end

  def password=(new_password)
    @password = new_password

    unless @password.blank?
      self.password_salt = SecureRandom.base64(32)
      self.hashed_password = Digest::SHA256.hexdigest(password_salt + password)
    end
  end

  def member_of_admins?
    groups.admins_group.present?
  end

  def refresh_reset_password_token
    self.reset_password_token = SecureRandom.hex(10)
    self.reset_password_token_expires_at = 1.hour.from_now
    self.dont_clear_reset_password_token = true
    save(:validate => false)
  end

  def refresh_remember_token
    self.remember_token = SecureRandom.base64(32)
    save(:validate => false)
  end

  def forget_me
    self.remember_token = nil
    save(:validate => false)
  end

  def name_is_blank?
    self.name.blank?
  end

  def self.authenticate(name, password)
    return nil if name.blank? || password.blank?
    user = find_by_name(name) or return nil
    hash = Digest::SHA256.hexdigest(user.password_salt + password)
    hash == user.hashed_password ? user : nil
  end

  def self.no_admin_yet?
    find_by_is_admin(true).blank?
  end

  private

  def set_signup_token
    self.signup_token = SecureRandom.hex(10)
    self.signup_token_expires_at = 2.weeks.from_now
  end

  def clear_signup_token
    unless self.name.blank?
      self.signup_token = nil
      self.signup_token_expires_at = nil
    end
  end

  def clear_reset_password_token
    self.reset_password_token = nil
    self.reset_password_token_expires_at = nil
  end

  def create_root_folder_and_admins_group
    Folder.create(:name => 'Root folder')
    groups << Group.create(:name => 'Admins')
  end

  def dont_destroy_admin
    raise "Can't delete original admin user" if is_admin
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_admin, :except => [:edit, :update]
  before_action :require_existing_user, :only => [:edit, :update, :destroy, :extend]
  before_action :require_deleted_user_isnt_admin, :only => :destroy

  def index
    @users = User.where.not(:name => nil).order('name')
    @new_users = User.where(:name => nil).order('email')
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(permitted_params.user)

    if @user.save
      UserMailer.signup_email(@user).deliver_now
      redirect_to users_url
    else
      render :action => 'new'
    end
  end

  # Note: @user is set in require_existing_user
  def edit
  end

  # Note: @user is set in require_existing_user
  def update
    if @user.update_attributes(permitted_params.user.merge({ :password_required => false }))
      redirect_to edit_user_url(@user), :notice => t(:your_changes_were_saved)
    else
      render :action => 'edit'
    end
  end

  # Note: @user is set in require_existing_user
  def extend
    @user.signup_token_expires_at = @user.signup_token_expires_at + 2.weeks
    @user.save(:validate => false)
    redirect_to users_url
  end

  # Note: @user is set in require_existing_user
  def destroy
    @user.destroy
    redirect_to users_url
  end

  private

  def require_existing_user
    if current_user.member_of_admins? && params[:id] != current_user.id.to_s
      @title = '编辑用户'
      @user = User.find(params[:id])
    else
      @title = '账号设置'
      @user = current_user
    end
  rescue ActiveRecord::RecordNotFound
    redirect_to users_url, :alert => t(:user_already_deleted)
  end

  def require_deleted_user_isnt_admin
    if @user.is_admin
      redirect_to users_url, :alert => t(:admin_user_cannot_be_deleted)
    end
  end
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= f.error_messages %>
  <% unless @user.new_record? -%>
  <div class="form__row">
    <div class="form__label">
      <%= f.label :name, t(:'用户名') %>
    </div>
    <div class="form__control">
      <%= f.text_field :name, { :class => 'text_input' } %>
    </div>
  </div>
  <% end -%>
  <div class="form__row">
    <div class="form__label">
      <%= f.label :email, t(:'电子邮箱') %>
    </div>
    <div class="form__control">
      <%= f.text_field :email, { :class => 'text_input' } %>
    </div>
  </div>
  <% unless @user.new_record? -%>
  <div class="form__row">
    <div class="form__label">
      <%= f.label :password, t(:'新密码') %>
    </div>
    <div class="form__control">
      <%= f.password_field :password, { :class => 'text_input' } %>
    </div>
  </div>

  <div class="form__row">
    <div class="form__label">
      <%= f.label :confirm_password, t(:'确认密码') %>
    </div>
    <div class="form__control">
      <%= f.password_field :password_confirmation, { :class => 'text_input' } %>
    </div>
  </div>
  <% end -%>
  <% if signed_in? && current_user.member_of_admins? -%>
  <p class="title--level1">
    <%= t :'已加入的群组' %>:
    <span class="user_groups">
    <% if @user.is_admin -%>
      <span class="disabled">
        <%= hidden_field_tag 'user[group_ids][]', Group.admins_group.id %>
        <input type="checkbox" checked="checked" disabled="disabled" /><label>Admins</label>
      </span>
      <%= f.collection_check_boxes :group_ids, Group.all_except_admins, :id, :name %>
    <% else -%>
      <%= f.collection_check_boxes :group_ids, Group.all, :id, :name %>
    <% end -%>
    </span>
  </p>
  <% end -%>
  <div class="form-btns clearfix">
    <button type="submit" class="button--light">保 存</button>
  <% if @user != current_user -%>
    <%= link_to '返 回', users_url, { :class => 'button--light default link-to-button' } %>
  <% end -%>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="form__wrapper--center form__wrapper--normal">
    <% content_for :title, @title -%>
    <h1 class="title--level1"><%= content_for :title %></h1>
    <%= render 'form' %>
</div>

app/views/users/index.html.erb
<% content_for :title, t(:users) -%>

<h1 class="title--level1"><%= content_for :title %></h1>
<p>
  <span class="user_menu"><%= image_tag('user_add.png', :alt => t(:create_a_new_user)) %> <%= link_to t(:create_a_new_user), new_user_path %></span>
</p>

<h3 class="title--level1"><%= t :active_users %></h3>
<table style="width:100%;" class="table--stripes">
  <tr>
    <th></th>
    <th><%= t :name %></th>
    <th><%= t :email %></th>
    <th></th>
  </tr>
<% @users.each do |user| -%>
  <tr class="<%= cycle('even','odd') %>">
    <td><%= image_tag('user.png') %></td>
    <td class="user_name"><%= user.name %></td>
    <td class="user_email"><%= user.email %></td>
    <td>
      <%= link_to image_tag('edit.png', :alt => t(:edit)), edit_user_path(user), :title => t(:edit) %>&nbsp;
    <% unless user.is_admin -%>
      <%= link_to image_tag('delete.png', :alt => t(:delete_item)), user_path(user), :method => :delete, :data => { :confirm => t(:are_you_sure) }, :title => t(:delete_item) %>
    <% end -%>
    </td>
  </tr>
<% end -%>
</table>

<% unless @new_users.blank? -%>
<h3><%= t :invited_users %></h3>
<table style="width:100%;border:1px solid #eee;">
  <tr>
    <th></th>
    <th><%= t :email %></th>
    <th><%= t :expiration_date %></th>
    <th></th>
  </tr>
<% @new_users.each do |user| -%>
  <tr class="<%= cycle('even','odd') %>">
    <td><%= image_tag('user.png') %></td>
    <td class="user_email"><%= user.email %></td>
    <td class="user_expiration">
    <% if user.signup_token_expires_at > Time.now -%>
      <%= l user.signup_token_expires_at, :format => :very_short %>
    <% else -%>
      <span class="red"><%= l user.signup_token_expires_at, :format => :very_short %></span>
    <% end -%>
    </td>
    <td>
      <%= link_to image_tag('extend.png', :alt => t(:extend_expiration_date)), extend_user_path(user), :method => :put, :title => t(:extend_expiration_date) %>&nbsp;
    <% unless user.is_admin -%>
      <%= link_to image_tag('delete.png', :alt => t(:delete_item)), user_path(user), :method => :delete, :data => { :confirm => t(:are_you_sure) }, :title => t(:delete_item) %>
    <% end -%>
    </td>
  </tr>
<% end -%>
</table>
<% end -%>

app/views/users/new.html.erb
<div class="form__wrapper--center form__wrapper--normal">
    <% content_for :title, t(:new_user) -%>

    <h1 class="title--level1"><%= content_for :title %></h1>
    <%= render 'form' %>
</div>