config/routes.rb
Boxroom::Application.routes.draw do
  get '/file_exists', :to => 'files#exists'
  get '/signin', :to => 'sessions#new', :as => 'signin'
  get '/home', :to => 'home#index', :as => 'home', path: '/home'
  delete '/signout', :to => 'sessions#destroy'

  # Resources
  resources :admins, :only => [:new, :create]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :reset_password, :except => [:index, :show, :destroy]
  resources :signup, :only => [:edit, :update]
  resources :groups, :except => :show
  resources :files, :except => [:index, :new, :create] do
    get :preview
  end
  resources :share_links, :only => [:index, :show, :destroy]

  resources :users, :except => :show do
    put :extend, :on => :member
  end

  resources :clipboard, :only => [:create, :destroy] do
    post :copy, :on => :member
    post :move, :on => :member
    put :reset, :on => :member
  end

  # Update a collection of permissions
  resources :permissions, :only => :update_multiple do
    put :update_multiple, :on => :collection
  end

  # Nested resources
  resources :folders, :shallow => true, :except => [:new, :create] do
    resources :folders, :only => [:new, :create]
    resources :files, :only => [:new, :create]
  end

  resources :files, :shallow => true, :only => :show do
    resources :share_links, :only => [:new, :create]
  end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => "folders#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end

end

app/views/home/index.html.erb
<div class="menu--root">
    <div class="menu__row--root">
        <div class="menu__item--root">
            <div class="menu__icon--root">
                <%= link_to image_tag('root_icon_1.png', :alt => 'Products'), "http://code.cdavatar.com:8081/" %>
                <div class="menu__light--root"></div>
            </div>
            <div class="menu__name--root">
                产品设计文档
            </div>
        </div>
        <div class="row__sep--root"></div>

        <div class="menu__item--root">
            <div class="menu__icon--root">
                <%= link_to image_tag('root_icon_2.png', :alt => 'Repos'), "http://code.cdavatar.com:8080/" %>
                <div class="menu__light--root"></div>
            </div>
            <div class="menu__name--root">
                代码仓库
            </div>
        </div>
        <div class="row__sep--root"></div>

        <div class="menu__item--root">
            <div class="menu__icon--root">
                <%= link_to image_tag('root_icon_5.png', :alt => 'exmail'), "http://exmail.qq.com/cgi-bin/frame_html" %>
                <div class="menu__light--root"></div>
            </div>
            <div class="menu__name--root">
                邮箱
            </div>
        </div>
        <div class="row__sep--root"></div>

        <div class="menu__item--root">
            <div class="menu__icon--root">
                <%= link_to image_tag('root_icon_3.png', :alt => 'Dinners'), "https://docs.google.com/spreadsheets/d/1SEnuCZF-QvlfJkNcd4i8nGu7THdCp_Ovav-vvq6YBQk/edit?usp=sharing" %>
                <div class="menu__light--root"></div>
            </div>
            <div class="menu__name--root">
                餐补
            </div>
        </div>

        <% if signed_in? -%>

        <% end -%>
    </div>

    <div class="menu__row--root">
        <% if signed_in? -%>
            <div class="menu__item--root">
                <div class="menu__icon--root">
                    <%= link_to image_tag('root_icon_4.png', :alt => 'folders'), folders_path %>
                    <div class="menu__light--root"></div>
                </div>
                <div class="menu__name--root">
                    文件
                </div>
            </div>
            <div class="row__sep--root"></div>

            <div class="menu__item--root">
                <div class="menu__icon--root">
                    <%= link_to image_tag('root_icon_6.png', :alt => 'Dinners'), "http://code.cdavatar.com:8083/folders/136" %>
                    <div class="menu__light--root"></div>
                </div>
                <div class="menu__name--root">
                    工作总结
                </div>
            </div>
            <div class="row__sep--root"></div>

            <div class="menu__item--root">
                <div class="menu__icon--root">
                    <%= link_to image_tag('root_icon_8.png', :alt => 'waiting'), "http://code.cdavatar.com:8083/folders/21" %>
                    <div class="menu__light--root"></div>
                </div>
                <div class="menu__name--root">
                    电子书
                </div>
            </div>
            <div class="row__sep--root"></div>

            <div class="menu__item--root">
                <div class="menu__icon--root">
                    <%= link_to image_tag('root_icon_7.png', :alt => 'waiting'), "http://code.cdavatar.com:8083/folders/3" %>
                    <div class="menu__light--root"></div>
                </div>
                <div class="menu__name--root">
                    分享会议存档
                </div>
            </div>
        <% end -%>

    </div>

    <div class="menu__row--root">
        <% if signed_in? -%>
            <% if current_user.member_of_admins? -%>
                <div class="menu__item--root">
                    <div class="menu__icon--root">
                        <%= link_to image_tag('root_icon_9.png', :alt => 'users'), users_path %>
                        <div class="menu__light--root"></div>
                    </div>
                    <div class="menu__name--root">
                        用户
                    </div>
                </div>
                <div class="row__sep--root"></div>

                <div class="menu__item--root">
                    <div class="menu__icon--root">
                        <%= link_to image_tag('root_icon_9.png', :alt => 'groups'), groups_path %>
                        <div class="menu__light--root"></div>
                    </div>
                    <div class="menu__name--root">
                        分组
                    </div>
                </div>
                <div class="row__sep--root"></div>

                <div class="menu__item--root">
                    <div class="menu__icon--root">
                        <%= link_to image_tag('root_icon_9.png', :alt => 'share_links'), share_links_path %>
                        <div class="menu__light--root"></div>
                    </div>
                    <div class="menu__name--root">
                        分享链接
                    </div>
                </div>
                <div class="row__sep--root"></div>
            <% end -%>
        <% end -%>

        <div class="menu__item--root hidden">
            <div class="menu__icon--root">
                <%= link_to image_tag('root_icon_9.png', :alt => 'waiting'), "" %>
                <div class="menu__light--root"></div>
            </div>
            <div class="menu__name--root">
                待定
            </div>
        </div>

    </div>
</div>